#!/bin/bash 
#PBS -N Serial_Example
#PBS -o /lustre/work/tutorial/scratch
#PBS -e /lustre/work/tutorial/scratch
#PBS -l select=1:ncpus=16:mem=4gb
#PBS -l walltime=00:30:00
#PBS -u tutorial
#PBS -M connor.bottrell@ipmu.jp
#PBS -m ae
#PBS -V
#PBS -q mini

# activate Python 3
source /home/anaconda3/bin/activate
# you can set environment variables in the job script
export HPC_DIR=/lustre/work/tutorial/HPC_IPMU
cd $HPC_DIR/Code/OpenMP
# run program
python OpenMP_Example.py
